# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

database:
  hostname: localhost
  port: 5432
  username: postgres
  password: ${PGPASSWORD}
  app_db_name: postmark
  connectionTimeoutMillis: 3000
  app_db_client: knex
  migrate:
    - npx knex migrate:latest
  rollback:
    - npx knex migrate:rollback
env:
  POSTMARK_USER: ${POSTMARK_USER}
  POSTMARK_PASSWORD: ${POSTMARK_PASSWORD}
  SENDER_EMAIL: ${SENDER_EMAIL}
  RECIPIENT_EMAIL: ${RECIPIENT_EMAIL}
runtimeConfig:
  entrypoints:
    - dist/operations.js